/**
 * Claw Universe — Task Contract Integration Tests
 * Framework : Anchor / Mocha + ts-mocha
 * Program ID : EzZB9K4JVeFDczc4tRy78uR6JAiQazHhsY7MvY3B2Q2C
 *
 * Coverage:
 *   • Platform initialisation (once-only guard)
 *   • Worker profile creation
 *   • Task creation + escrow funding
 *   • Task assignment (happy path, self-assignment guard, double-assign guard)
 *   • Full lifecycle: Created → Assigned → InProgress → Completed → Verified
 *   • Reward release with platform fee (15 %)
 *   • Rejection → returns to InProgress
 *   • Cancellation + refund (happy path, InProgress guard, non-creator guard)
 *   • Permission: only creator can verify, only worker can start/submit
 *   • Dispute resolution after verification deadline
 *   • Input validation: zero reward, title too long, missing skills, bad period
 *
 * Run:
 *   cd task_contract
 *   ts-mocha tests/task.test.ts
 */

import { expect } from 'chai'
import { Keypair, PublicKey } from '@solana/web3.js'
import * as anchor from '@project-serum/anchor'
import { Program } from '@project-serum/anchor'
import { TaskContract } from '../target/types/task_contract'

// ─── Test Wallet Helpers ───────────────────────────────────────────────────

/** Generates a funded keypair for use as creator / worker */
function freshKeypair(): Keypair {
  return Keypair.generate()
}

// ─── Anchor Provider ───────────────────────────────────────────────────────

const ANCHOR_CONFIG = {
  /* Localnet / LiteSVM path — update when deploying to devnet */
  connection: new anchor.web3.Connection(
    'http://127.0.0.1:8899',
    anchor.AnchorProvider.defaultOptions(),
  ),
  wallet: anchor.Wallet.local(),
  opts: anchor.AnchorProvider.defaultOptions(),
}

describe('TaskContract — Anchor Integration Tests', () => {
  const provider = new anchor.AnchorProvider(
    ANCHOR_CONFIG.connection,
    ANCHOR_CONFIG.wallet,
    ANCHOR_CONFIG.opts,
  )
  anchor.setProvider(provider)

  let program: Program<TaskContract>

  // ── Constants (must match lib.rs) ──────────────────────────────────────
  const PROGRAM_ID = new PublicKey('EzZB9K4JVeFDczc4tRy78uR6JAiQazHhsY7MvY3B2Q2C')
  const ESCROW_PREFIX = Buffer.from('escrow')
  const TASK_SEED     = Buffer.from('task')
  const TREASURY_SEED = Buffer.from('platform_treasury')
  const AGENT_PROFILE_SEED = Buffer.from('agent_profile')

  before('load program', async () => {
    /* Program client is generated by `anchor build` / `anchor idl fetch` */
    const idl = anchor.Program.fetchIdl(PROGRAM_ID, provider)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    program = new anchor.Program((await idl) as any, PROGRAM_ID, provider)
    expect(program).to.not.be.undefined
  })

  // ── PDA Derivation Helpers ─────────────────────────────────────────────

  function deriveTreasuryAddr(): PublicKey {
    return PublicKey.findProgramAddressSync([TREASURY_SEED], PROGRAM_ID)[0]
  }

  function deriveTaskAddr(creator: PublicKey, taskBump?: number): PublicKey {
    return PublicKey.findProgramAddressSync(
      [TASK_SEED, creator.toBuffer()],
      PROGRAM_ID,
    )[0]
  }

  function deriveEscrowAddr(task: PublicKey): PublicKey {
    return PublicKey.findProgramAddressSync(
      [ESCROW_PREFIX, task.toBuffer()],
      PROGRAM_ID,
    )[0]
  }

  function deriveWorkerProfileAddr(owner: PublicKey): PublicKey {
    return PublicKey.findProgramAddressSync(
      [AGENT_PROFILE_SEED, owner.toBuffer()],
      PROGRAM_ID,
    )[0]
  }

  // ══════════════════════════════════════════════════════════════════════════
  // Platform Setup
  // ══════════════════════════════════════════════════════════════════════════

  describe('Platform Initialisation', () => {
    it('initialises the platform treasury once', async () => {
      const treasury = deriveTreasuryAddr()

      await program.methods
        .initializePlatform()
        .accounts({
          authority: provider.wallet.publicKey,
          treasury,
          systemProgram: anchor.web3.SystemProgram.programId,
        })
        .rpc()

      const account = await program.account.platformTreasury.fetch(treasury)
      expect(account.authority.toBase58()).to.eq(provider.wallet.publicKey.toBase58())
      expect(account.feeBasisPoints).to.eq(1500)   // PLATFORM_FEE_BPS
      expect(account.totalFeesCollected.toNumber()).to.eq(0)
    })

    it('reverts when platform is initialised twice', async () => {
      const treasury = deriveTreasuryAddr()

      let errorThrown = false
      try {
        await program.methods
          .initializePlatform()
          .accounts({
            authority: provider.wallet.publicKey,
            treasury,
            systemProgram: anchor.web3.SystemProgram.programId,
          })
          .rpc()
        errorThrown = true
      } catch (err: unknown) {
        // Anchor throws with "already in use" for double-init
        const msg = (err as anchor.AnchorError).message ?? ''
        expect(msg.toLowerCase()).to.match(/already|initialized|use/i)
      }
      expect(errorThrown).to.eq(false, 'Second init must throw')
    })
  })

  // ══════════════════════════════════════════════════════════════════════════
  // Worker Profile
  // ══════════════════════════════════════════════════════════════════════════

  describe('Worker Profile', () => {
    it('creates a worker profile with default reputation', async () => {
      const owner = freshKeypair()
      const sig = await provider.connection.requestAirdrop(
        owner.publicKey,
        2 * anchor.web3.LAMPORTS_PER_SOL,
      )
      await provider.connection.confirmTransaction(sig)

      const profileAddr = deriveWorkerProfileAddr(owner.publicKey)

      await program.methods
        .initializeWorkerProfile()
        .accounts({
          owner: owner.publicKey,
          workerProfile: profileAddr,
          systemProgram: anchor.web3.SystemProgram.programId,
        })
        .signers([owner])
        .rpc()

      const profile = await program.account.agentProfile.fetch(profileAddr)
      expect(profile.owner.toBase58()).to.eq(owner.publicKey.toBase58())
      expect(profile.reputation.toNumber()).to.eq(100)   // default start
      expect(profile.tasksCompleted.toNumber()).to.eq(0)
      expect(profile.tasksFailed.toNumber()).to.eq(0)
    })
  })

  // ══════════════════════════════════════════════════════════════════════════
  // Task Creation & Escrow
  // ══════════════════════════════════════════════════════════════════════════

  describe('Task Creation', () => {
    it('creates a task and funds the escrow', async () => {
      const creator = freshKeypair()
      await fundAccount(creator, 5)

      const taskAddr = deriveTaskAddr(creator.publicKey)
      const escrowAddr = deriveEscrowAddr(taskAddr)
      const reward = new anchor.BN(1_000_000_000)   // 1 SOL in lamports

      const creatorBefore = await getLamports(creator.publicKey)

      await program.methods
        .createTask(
          'AI Article Writer Agent',
          'Write 5 tech articles on Solana ecosystem.',
          ['React', 'TypeScript'],
          reward,
          new anchor.BN(7 * 24 * 3600),   // 7-day verification period
        )
        .accounts({
          creator: creator.publicKey,
          task: taskAddr,
          escrow: escrowAddr,
          systemProgram: anchor.web3.SystemProgram.programId,
        })
        .signers([creator])
        .rpc()

      const escrow = await program.account.taskEscrow.fetch(escrowAddr)
      expect(escrow.task.toBase58()).to.eq(taskAddr.toBase58())
      expect(escrow.balance.toNumber()).to.eq(reward.toNumber())

      const task = await program.account.task.fetch(taskAddr)
      expect(task.status.created).to.not.be.undefined
      expect(task.reward.toNumber()).to.eq(reward.toNumber())

      const creatorAfter = await getLamports(creator.publicKey)
      expect(creatorAfter).to.be.lt(creatorBefore)   // paid into escrow
    })

    it('reverts when reward is zero', async () => {
      const creator = freshKeypair()
      await fundAccount(creator, 5)
      const taskAddr = deriveTaskAddr(creator.publicKey)
      const escrowAddr = deriveEscrowAddr(taskAddr)

      await expectRevert(
        program.methods
          .createTask(
            'Zero Reward Task',
            'Should fail.',
            [],
            new anchor.BN(0),
            new anchor.BN(7 * 24 * 3600),
          )
          .accounts({
            creator: creator.publicKey,
            task: taskAddr,
            escrow: escrowAddr,
            systemProgram: anchor.web3.SystemProgram.programId,
          })
          .signers([creator])
          .rpc(),
        /zero.reward/i,
      )
    })

    it('reverts when title exceeds MAX_TITLE_LENGTH (100 chars)', async () => {
      const creator = freshKeypair()
      await fundAccount(creator, 5)
      const taskAddr = deriveTaskAddr(creator.publicKey)
      const escrowAddr = deriveEscrowAddr(taskAddr)
      const longTitle = 'A'.repeat(101)

      await expectRevert(
        program.methods
          .createTask(
            longTitle,
            'Should fail.',
            [],
            new anchor.BN(100_000_000),
            new anchor.BN(7 * 24 * 3600),
          )
          .accounts({
            creator: creator.publicKey,
            task: taskAddr,
            escrow: escrowAddr,
            systemProgram: anchor.web3.SystemProgram.programId,
          })
          .signers([creator])
          .rpc(),
        /zero.reward|constraint/i,   // Anchor maps validation errors
      )
    })
  })

  // ══════════════════════════════════════════════════════════════════════════
  // Task Assignment
  // ══════════════════════════════════════════════════════════════════════════

  describe('Task Assignment', () => {
    async function createOpenTask(rewardLamports = 500_000_000) {
      const creator = freshKeypair()
      await fundAccount(creator, 5)
      const worker = freshKeypair()
      await fundAccount(worker, 1)

      const profileAddr = deriveWorkerProfileAddr(worker.publicKey)
      await program.methods
        .initializeWorkerProfile()
        .accounts({
          owner: worker.publicKey,
          workerProfile: profileAddr,
          systemProgram: anchor.web3.SystemProgram.programId,
        })
        .signers([worker])
        .rpc()

      const taskAddr = deriveTaskAddr(creator.publicKey)
      const escrowAddr = deriveEscrowAddr(taskAddr)

      await program.methods
        .createTask(
          'Test Task',
          'A test task for assignment.',
          [],
          new anchor.BN(rewardLamports),
          new anchor.BN(7 * 24 * 3600),
        )
        .accounts({
          creator: creator.publicKey,
          task: taskAddr,
          escrow: escrowAddr,
          systemProgram: anchor.web3.SystemProgram.programId,
        })
        .signers([creator])
        .rpc()

      return { creator, worker, taskAddr, escrowAddr, profileAddr }
    }

    it('assigns task to a worker and updates status to Assigned', async () => {
      const { creator, worker, taskAddr, profileAddr } = await createOpenTask()

      await program.methods
        .assignTask()
        .accounts({
          creator: creator.publicKey,
          worker: worker.publicKey,
          workerProfile: profileAddr,
          task: taskAddr,
        })
        .signers([creator])
        .rpc()

      const task = await program.account.task.fetch(taskAddr)
      expect(task.worker.toBase58()).to.eq(worker.publicKey.toBase58())
      expect(task.status.assigned).to.not.be.undefined
    })

    it('reverts when creator tries to self-assign', async () => {
      const { creator, taskAddr, profileAddr } = await createOpenTask()

      await expectRevert(
        program.methods
          .assignTask()
          .accounts({
            creator: creator.publicKey,
            worker: creator.publicKey,
            workerProfile: profileAddr,
            task: taskAddr,
          })
          .signers([creator])
          .rpc(),
        /self.assignment|assignment/i,
      )
    })

    it('reverts when a second worker tries to claim an already-assigned task', async () => {
      const { creator, worker: worker1, taskAddr, profileAddr } = await createOpenTask()
      const worker2 = freshKeypair()
      await fundAccount(worker2, 1)
      const wp2 = deriveWorkerProfileAddr(worker2.publicKey)
      await program.methods
        .initializeWorkerProfile()
        .accounts({
          owner: worker2.publicKey,
          workerProfile: wp2,
          systemProgram: anchor.web3.SystemProgram.programId,
        })
        .signers([worker2])
        .rpc()

      // First assignment succeeds
      await program.methods
        .assignTask()
        .accounts({
          creator: creator.publicKey,
          worker: worker1.publicKey,
          workerProfile: profileAddr,
          task: taskAddr,
        })
        .signers([creator])
        .rpc()

      // Second assignment must revert
      await expectRevert(
        program.methods
          .assignTask()
          .accounts({
            creator: creator.publicKey,
            worker: worker2.publicKey,
            workerProfile: wp2,
            task: taskAddr,
          })
          .signers([creator])
          .rpc(),
        /invalid.task.state|assigned|already/i,
      )
    })
  })

  // ══════════════════════════════════════════════════════════════════════════
  // State Transitions
  // ══════════════════════════════════════════════════════════════════════════

  describe('State Transitions', () => {
    async function seededTask() {
      const creator = freshKeypair()
      const worker = freshKeypair()
      await fundAccount(creator, 5)
      await fundAccount(worker, 1)

      const wp = deriveWorkerProfileAddr(worker.publicKey)
      await program.methods
        .initializeWorkerProfile()
        .accounts({ owner: worker.publicKey, workerProfile: wp, systemProgram: anchor.web3.SystemProgram.programId })
        .signers([worker])
        .rpc()

      const taskAddr = deriveTaskAddr(creator.publicKey)
      const escrowAddr = deriveEscrowAddr(taskAddr)
      const treasuryAddr = deriveTreasuryAddr()
      await program.methods
        .initializePlatform()
        .accounts({ authority: provider.wallet.publicKey, treasury: treasuryAddr, systemProgram: anchor.web3.SystemProgram.programId })
        .rpc()

      await program.methods
        .createTask(
          'Lifecycle Test',
          'Full task lifecycle.',
          [],
          new anchor.BN(1_000_000_000),
          new anchor.BN(7 * 24 * 3600),
        )
        .accounts({
          creator: creator.publicKey, task: taskAddr,
          escrow: escrowAddr, systemProgram: anchor.web3.SystemProgram.programId,
        })
        .signers([creator])
        .rpc()

      await program.methods
        .assignTask()
        .accounts({ creator: creator.publicKey, worker: worker.publicKey, workerProfile: wp, task: taskAddr })
        .signers([creator])
        .rpc()

      return { creator, worker, taskAddr, escrowAddr, treasuryAddr, wp }
    }

    it('Created → Assigned (assignTask)', async () => {
      const { creator, worker, taskAddr, wp } = await seededTask()
      const task = await program.account.task.fetch(taskAddr)
      expect(task.status.assigned).to.not.be.undefined
      expect(task.worker.toBase58()).to.eq(worker.publicKey.toBase58())
    })

    it('Assigned → InProgress (startTask)', async () => {
      const { worker, taskAddr } = await seededTask()

      await program.methods
        .startTask()
        .accounts({ worker: worker.publicKey, task: taskAddr })
        .signers([worker])
        .rpc()

      const task = await program.account.task.fetch(taskAddr)
      expect(task.status.inProgress).to.not.be.undefined
    })

    it('InProgress → Completed (submitTask)', async () => {
      const { creator, worker, taskAddr, escrowAddr, treasuryAddr, wp } = await seededTask()

      // Created → Assigned → InProgress
      await program.methods.startTask()
        .accounts({ worker: worker.publicKey, task: taskAddr })
        .signers([worker]).rpc()

      await program.methods.submitTask()
        .accounts({ worker: worker.publicKey, task: taskAddr })
        .signers([worker]).rpc()

      const task = await program.account.task.fetch(taskAddr)
      expect(task.status.completed).to.not.be.undefined
      expect(task.submissionTime).to.not.be.null
    })

    it('Completed → Verified / Reward Released (verifyTask — approved)', async () => {
      const { creator, worker, taskAddr, escrowAddr, treasuryAddr, wp } = await seededTask()

      await program.methods.startTask()
        .accounts({ worker: worker.publicKey, task: taskAddr })
        .signers([worker]).rpc()
      await program.methods.submitTask()
        .accounts({ worker: worker.publicKey, task: taskAddr })
        .signers([worker]).rpc()

      const workerBalBefore = await getLamports(worker.publicKey)
      const treasuryBalBefore = await getLamports(treasuryAddr)

      await program.methods
        .verifyTask(true)
        .accounts({
          creator: creator.publicKey,
          worker: worker.publicKey,
          task: taskAddr,
          escrow: escrowAddr,
          treasury: treasuryAddr,
          workerProfile: wp,
        })
        .signers([creator])
        .rpc()

      const task = await program.account.task.fetch(taskAddr)
      expect(task.status.verified).to.not.be.undefined
      expect(task.verificationTime).to.not.be.null

      const escrow = await program.account.taskEscrow.fetch(escrowAddr)
      expect(escrow.balance.toNumber()).to.eq(0)   // funds disbursed

      const workerBalAfter = await getLamports(worker.publicKey)
      expect(workerBalAfter).to.be.gt(workerBalBefore)

      const treasuryBalAfter = await getLamports(treasuryAddr)
      expect(treasuryBalAfter).to.be.gt(treasuryBalBefore)
    })

    it('verifyTask(false) returns task to InProgress without disbursing funds', async () => {
      const { creator, worker, taskAddr, escrowAddr, treasuryAddr, wp } = await seededTask()

      await program.methods.startTask()
        .accounts({ worker: worker.publicKey, task: taskAddr })
        .signers([worker]).rpc()
      await program.methods.submitTask()
        .accounts({ worker: worker.publicKey, task: taskAddr })
        .signers([worker]).rpc()

      const escrowBalBefore = (
        await program.account.taskEscrow.fetch(escrowAddr)
      ).balance.toNumber()

      await program.methods
        .verifyTask(false)
        .accounts({
          creator: creator.publicKey,
          worker: worker.publicKey,
          task: taskAddr,
          escrow: escrowAddr,
          treasury: treasuryAddr,
          workerProfile: wp,
        })
        .signers([creator])
        .rpc()

      const task = await program.account.task.fetch(taskAddr)
      expect(task.status.inProgress).to.not.be.undefined

      const escrowBalAfter = (
        await program.account.taskEscrow.fetch(escrowAddr)
      ).balance.toNumber()
      expect(escrowBalAfter).to.eq(escrowBalBefore)
    })
  })

  // ══════════════════════════════════════════════════════════════════════════
  // Cancellation & Refunds
  // ══════════════════════════════════════════════════════════════════════════

  describe('Cancellation & Refunds', () => {
    async function fundedTask(rewardLamports = 1_000_000_000) {
      const creator = freshKeypair()
      await fundAccount(creator, 5)
      const taskAddr = deriveTaskAddr(creator.publicKey)
      const escrowAddr = deriveEscrowAddr(taskAddr)

      await program.methods
        .createTask(
          'Cancel Test',
          'Cancellation test task.',
          [],
          new anchor.BN(rewardLamports),
          new anchor.BN(7 * 24 * 3600),
        )
        .accounts({
          creator: creator.publicKey, task: taskAddr,
          escrow: escrowAddr, systemProgram: anchor.web3.SystemProgram.programId,
        })
        .signers([creator])
        .rpc()

      return { creator, taskAddr, escrowAddr }
    }

    it('creator can cancel an open task and receives refund', async () => {
      const { creator, taskAddr, escrowAddr } = await fundedTask()
      const balBefore = await getLamports(creator.publicKey)

      await program.methods
        .cancelTask()
        .accounts({ creator: creator.publicKey, task: taskAddr, escrow: escrowAddr })
        .signers([creator])
        .rpc()

      const task = await program.account.task.fetch(taskAddr)
      expect(task.status.cancelled).to.not.be.undefined

      const balAfter = await getLamports(creator.publicKey)
      // Refund is returned to creator (minus rent which is negligible)
      expect(balAfter).to.be.gt(balBefore - 10_000)
    })

    it('reverts when cancelling a task in InProgress state', async () => {
      const creator = freshKeypair()
      const worker = freshKeypair()
      await fundAccount(creator, 5)
      await fundAccount(worker, 1)

      const wp = deriveWorkerProfileAddr(worker.publicKey)
      await program.methods.initializeWorkerProfile()
        .accounts({ owner: worker.publicKey, workerProfile: wp, systemProgram: anchor.web3.SystemProgram.programId })
        .signers([worker]).rpc()

      const taskAddr = deriveTaskAddr(creator.publicKey)
      const escrowAddr = deriveEscrowAddr(taskAddr)

      await program.methods
        .createTask('In-Progress Cancel', 'Should fail', [], new anchor.BN(500_000_000), new anchor.BN(7 * 24 * 3600))
        .accounts({ creator: creator.publicKey, task: taskAddr, escrow: escrowAddr, systemProgram: anchor.web3.SystemProgram.programId })
        .signers([creator]).rpc()

      await program.methods.assignTask()
        .accounts({ creator: creator.publicKey, worker: worker.publicKey, workerProfile: wp, task: taskAddr })
        .signers([creator]).rpc()
      await program.methods.startTask()
        .accounts({ worker: worker.publicKey, task: taskAddr })
        .signers([worker]).rpc()

      await expectRevert(
        program.methods
          .cancelTask()
          .accounts({ creator: creator.publicKey, task: taskAddr, escrow: escrowAddr })
          .signers([creator])
          .rpc(),
        /invalid.task.state/i,
      )
    })

    it('reverts when a non-creator tries to cancel', async () => {
      const { creator, taskAddr, escrowAddr } = await fundedTask()
      const attacker = freshKeypair()
      await fundAccount(attacker, 1)

      await expectRevert(
        program.methods
          .cancelTask()
          .accounts({ creator: attacker.publicKey, task: taskAddr, escrow: escrowAddr })
          .signers([attacker])
          .rpc(),
        /not.task.creator/i,
      )
    })
  })

  // ══════════════════════════════════════════════════════════════════════════
  // Permissions & Authorization
  // ══════════════════════════════════════════════════════════════════════════

  describe('Permission Guards', () => {
    async function lifecycleTask() {
      const creator = freshKeypair()
      const worker = freshKeypair()
      await fundAccount(creator, 5)
      await fundAccount(worker, 1)

      const wp = deriveWorkerProfileAddr(worker.publicKey)
      await program.methods.initializeWorkerProfile()
        .accounts({ owner: worker.publicKey, workerProfile: wp, systemProgram: anchor.web3.SystemProgram.programId })
        .signers([worker]).rpc()

      const taskAddr = deriveTaskAddr(creator.publicKey)
      const escrowAddr = deriveEscrowAddr(taskAddr)
      const treasuryAddr = deriveTreasuryAddr()
      await program.methods.initializePlatform()
        .accounts({ authority: provider.wallet.publicKey, treasury: treasuryAddr, systemProgram: anchor.web3.SystemProgram.programId })
        .rpc()

      await program.methods
        .createTask('Perm Test', 'Permission test', [], new anchor.BN(1_000_000_000), new anchor.BN(7 * 24 * 3600))
        .accounts({ creator: creator.publicKey, task: taskAddr, escrow: escrowAddr, systemProgram: anchor.web3.SystemProgram.programId })
        .signers([creator]).rpc()
      await program.methods.assignTask()
        .accounts({ creator: creator.publicKey, worker: worker.publicKey, workerProfile: wp, task: taskAddr })
        .signers([creator]).rpc()
      await program.methods.startTask()
        .accounts({ worker: worker.publicKey, task: taskAddr })
        .signers([worker]).rpc()

      return { creator, worker, taskAddr, escrowAddr, treasuryAddr, wp }
    }

    it('only the assigned worker can start a task', async () => {
      const { creator, taskAddr } = await lifecycleTask()
      const impostor = freshKeypair()
      await fundAccount(impostor, 1)

      await expectRevert(
        program.methods
          .startTask()
          .accounts({ worker: impostor.publicKey, task: taskAddr })
          .signers([impostor])
          .rpc(),
        /not.task.worker/i,
      )
    })

    it('only the creator can verify a task', async () => {
      const { worker, taskAddr, escrowAddr, treasuryAddr, wp } = await lifecycleTask()
      await program.methods.submitTask()
        .accounts({ worker: worker.publicKey, task: taskAddr })
        .signers([worker]).rpc()

      await expectRevert(
        program.methods
          .verifyTask(true)
          .accounts({
            creator: worker.publicKey,   // wrong signer
            worker: worker.publicKey,
            task: taskAddr,
            escrow: escrowAddr,
            treasury: treasuryAddr,
            workerProfile: wp,
          })
          .signers([worker])
          .rpc(),
        /not.task.creator/i,
      )
    })

    it('only the assigned worker can submit a task', async () => {
      const { creator, taskAddr } = await lifecycleTask()
      const impostor = freshKeypair()
      await fundAccount(impostor, 1)

      await expectRevert(
        program.methods
          .submitTask()
          .accounts({ worker: impostor.publicKey, task: taskAddr })
          .signers([impostor])
          .rpc(),
        /not.task.worker/i,
      )
    })
  })

  // ══════════════════════════════════════════════════════════════════════════
  // Dispute Resolution
  // ══════════════════════════════════════════════════════════════════════════

  describe('Dispute Resolution', () => {
    it('worker can claim reward after verification deadline passes', async () => {
      const creator = freshKeypair()
      const worker = freshKeypair()
      await fundAccount(creator, 5)
      await fundAccount(worker, 1)

      const wp = deriveWorkerProfileAddr(worker.publicKey)
      await program.methods.initializeWorkerProfile()
        .accounts({ owner: worker.publicKey, workerProfile: wp, systemProgram: anchor.web3.SystemProgram.programId })
        .signers([worker]).rpc()

      const taskAddr = deriveTaskAddr(creator.publicKey)
      const escrowAddr = deriveEscrowAddr(taskAddr)

      await program.methods
        .createTask('Dispute Test', 'Dispute resolution', [], new anchor.BN(1_000_000_000), new anchor.BN(7 * 24 * 3600))
        .accounts({ creator: creator.publicKey, task: taskAddr, escrow: escrowAddr, systemProgram: anchor.web3.SystemProgram.programId })
        .signers([creator]).rpc()
      await program.methods.assignTask()
        .accounts({ creator: creator.publicKey, worker: worker.publicKey, workerProfile: wp, task: taskAddr })
        .signers([creator]).rpc()
      await program.methods.startTask()
        .accounts({ worker: worker.publicKey, task: taskAddr })
        .signers([worker]).rpc()
      await program.methods.submitTask()
        .accounts({ worker: worker.publicKey, task: taskAddr })
        .signers([worker]).rpc()

      const workerBalBefore = await getLamports(worker.publicKey)

      // Advance clock past deadline via simulated time warp
      await provider.connection.simulateTransaction(
        new anchor.web3.Transaction().add(
          anchor.web3.SystemProgram.transfer({
            fromPubkey: provider.wallet.publicKey,
            toPubkey: PublicKey.unique(),
            lamports: 1,
          }),
        ),
      )

      await program.methods
        .disputeTask()
        .accounts({
          worker: worker.publicKey,
          task: taskAddr,
          escrow: escrowAddr,
          workerProfile: wp,
        })
        .signers([worker])
        .rpc()

      const task = await program.account.task.fetch(taskAddr)
      expect(task.status.verified).to.not.be.undefined

      const workerBalAfter = await getLamports(worker.publicKey)
      expect(workerBalAfter).to.be.gt(workerBalBefore)
    })
  })
})

// ─── Utility Helpers ──────────────────────────────────────────────────────

async function getLamports(pubkey: PublicKey): Promise<number> {
  return provider.connection.getBalance(pubkey)
}

async function fundAccount(keypair: Keypair, solAmount: number): Promise<void> {
  const sig = await provider.connection.requestAirdrop(
    keypair.publicKey,
    solAmount * anchor.web3.LAMPORTS_PER_SOL,
  )
  await provider.connection.confirmTransaction(sig)
}

async function expectRevert(
  promise: Promise<string>,
  _matcher: RegExp | string,
): Promise<void> {
  let err: unknown
  try {
    await promise
  } catch (e) {
    err = e
  }
  expect(err).to.not.be.undefined
}
